name: Publish info page

on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'

jobs:
  deploy:
    name: Build and deploy info.yukkuricraft.net
    runs-on: ubuntu-latest
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Checkout
      uses: actions/checkout@master

    - name: Yarn Install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Yarn Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Deploy-Info-Dev
      if: steps.extract_branch.outputs.branch == 'dev'
      uses: s0/git-publish-subdir-action@v2.0.0
      env:
        REPO: self
        BRANCH: gh-pages-dev
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy-Info-Prod
      if: steps.extract_branch.outputs.branch == 'master'
      uses: s0/git-publish-subdir-action@v2.0.0
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
